services:
  keshar-world-admin-backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      NODE_ENV: development
    ports:
      - "3029:3029"
    volumes:
      - .:/home/app/keshar-world-admin-backend
      - /home/app/keshar-world-admin-backend/node_modules
    entrypoint: npm start
