services:
  hsc-gen-main-backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
    volumes:
      - .:/home/app/hsc-gen-main-backend
      - /home/app/hsc-gen-main-backend/node_modules
    entrypoint: npm start
